# Generated by Django 2.2.2 on 2019-06-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190627_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
