# Generated by Django 2.2.2 on 2019-07-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190627_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='catalog.OrderProducts', to='catalog.Product'),
        ),
    ]
